# As specified in the eWaterCycle setup guide:
# https://ewatercycle.readthedocs.io/en/latest/system_setup.html#conda-environment
---
name: ewatercycle
channels:
  - conda-forge
dependencies:
  - python=3.10
  - esmvaltool-python>=2.3.0